name: CI

on:
  push:
    branches: [main, builder-bob]
  pull_request:
    branches: [main, builder-bob]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install library dependencies
        run: cd neoui && npm ci --legacy-peer-deps

      - name: Run linter
        run: cd neoui && npm run lint

      - name: Run type check
        run: cd neoui && npm run typecheck

      - name: Run tests
        run: cd neoui && npm test

      - name: Build library
        run: cd neoui && npm run build

  example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci --legacy-peer-deps

      - name: Install example dependencies
        run: cd example && npm ci --legacy-peer-deps

      - name: Build example
        run: cd example && npm run web
